import type { GlassPrismPresetId, GlassPrismState } from "./GlassPrismState";
interface Actions { change(background?: boolean): void; preset(id: GlassPrismPresetId): void; reset(): void; export(): void; sequence(): void }
const control = (label: string, path: string, min: number, max: number, step: number) => `<div class="property-row"><label>${label}</label><input aria-label="${label}" type="range" data-prism-bind="${path}" min="${min}" max="${max}" step="${step}"><input aria-label="${label} 값" type="number" data-prism-bind="${path}" min="${min}" max="${max}" step="${step}"></div>`;
const pathValue = (state: GlassPrismState, path: string): unknown => path.split(".").reduce<unknown>((current, key) => (current as Record<string, unknown>)[key], state);
function setPath(state: GlassPrismState, path: string, value: string | number | boolean): void { const keys = path.split("."); const target = keys.slice(0, -1).reduce<Record<string, unknown>>((current, key) => current[key] as Record<string, unknown>, state as unknown as Record<string, unknown>); target[keys.at(-1) as string] = value; }

export class GlassPrismPanel {
  constructor(private readonly root: HTMLElement, private readonly state: GlassPrismState, private readonly actions: Actions) { this.root.innerHTML = this.template(); this.bind(); this.sync(); }
  sync(): void {
    this.root.querySelectorAll<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>("[data-prism-bind]").forEach((input) => { const value = pathValue(this.state, input.dataset.prismBind ?? ""); if (input instanceof HTMLInputElement && input.type === "checkbox") input.checked = Boolean(value); else input.value = String(value); });
    const preset = this.root.querySelector<HTMLSelectElement>("[data-prism-preset]"); if (preset) preset.value = this.state.preset;
    const size = this.root.querySelector<HTMLElement>("[data-prism-output-size]"); if (size) size.textContent = `${this.state.artboard.width} × ${this.state.artboard.height}px`;
    const textControls = this.root.querySelector<HTMLElement>("[data-prism-text-controls]"); if (textControls) textControls.hidden = this.state.content.mode !== "text";
  }
  focusExport(): void { this.root.querySelector<HTMLElement>("[data-prism-output]")?.scrollIntoView({ behavior: "smooth", block: "start" }); }
  private bind(): void {
    this.root.querySelector<HTMLSelectElement>("[data-prism-preset]")?.addEventListener("change", (event) => this.actions.preset((event.currentTarget as HTMLSelectElement).value as GlassPrismPresetId));
    this.root.querySelectorAll<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>("[data-prism-bind]").forEach((input) => input.addEventListener("input", (event) => {
      const target = event.currentTarget as HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement; const path = target.dataset.prismBind ?? "";
      const value = target instanceof HTMLInputElement && target.type === "checkbox" ? target.checked : target instanceof HTMLInputElement && target.type === "number" || target instanceof HTMLInputElement && target.type === "range" ? Number(target.value) : target.value;
      setPath(this.state, path, value); this.root.querySelectorAll<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>(`[data-prism-bind="${path}"]`).forEach((peer) => { if (peer !== target) { if (peer instanceof HTMLInputElement && peer.type === "checkbox") peer.checked = Boolean(value); else peer.value = String(value); } });
      this.actions.change(path.startsWith("content.")); this.sync();
    }));
    this.root.querySelector("[data-prism-reset]")?.addEventListener("click", () => this.actions.reset()); this.root.querySelector("[data-prism-export]")?.addEventListener("click", () => this.actions.export()); this.root.querySelector("[data-prism-sequence]")?.addEventListener("click", () => this.actions.sequence());
  }
  private template(): string {
    return `<aside class="control-dock light-field-panel glass-prism-panel" data-mode-panel="glass-prism">
      <div class="inspector-header"><div><strong>GLASS PRISM</strong><span>WEBGL2 · RGB REFRACTION</span></div></div><div class="inspector-views">
      <section class="studio-section"><header><h2>프리셋</h2><p>유리 굴절과 분산의 시작점</p></header><label class="select-row"><span>프리셋</span><select aria-label="Glass Prism 프리셋" data-prism-preset><option value="clear-glass">Clear Glass</option><option value="rgb-prism">RGB Prism</option><option value="frosted-prism">Frosted Prism</option><option value="dark-crystal">Dark Crystal</option></select></label><button class="wide-button" data-prism-reset>기본값으로 초기화</button></section>
      <section class="studio-section"><header><h2>유리</h2><p>두께 기반 RGB 굴절과 가장자리 반사</p></header>${control("IOR", "material.ior", 1.01, 2.2, .005)}${control("분산", "material.dispersion", 0, .16, .001)}${control("투명도", "material.transparency", 0, 1, .01)}${control("베벨", "geometry.bevel", 0, .2, .002)}${control("거칠기", "material.roughness", 0, .4, .005)}${control("반사", "material.reflection", 0, 1, .01)}${control("굴절 강도", "material.refractionStrength", 0, 1.5, .01)}${control("흡수", "material.absorption", 0, 1, .01)}<label class="select-row"><span>유리 색조</span><input aria-label="유리 색조" type="color" data-prism-bind="material.tint"></label></section>
      <section class="studio-section"><header><h2>표면 질감</h2><p>투명 유리의 미세 굴곡이 반사와 굴절을 흔듭니다</p></header>${control("질감 강도", "material.surfaceTextureStrength", 0, .6, .005)}${control("질감 크기", "material.surfaceTextureScale", 1, 16, .1)}</section>
      <section class="studio-section"><header><h2>배경</h2><p>배경 그래픽이 두 유리면을 통과하며 굴절됩니다</p></header><label class="select-row"><span>콘텐츠</span><select aria-label="배경 콘텐츠" data-prism-bind="content.mode"><option value="text">텍스트</option><option value="background">색상만</option></select></label><div data-prism-text-controls><label class="text-control"><span>배경 텍스트</span><textarea aria-label="배경 텍스트" data-prism-bind="content.text"></textarea></label><label class="select-row"><span>텍스트 색상</span><input aria-label="텍스트 색상" type="color" data-prism-bind="content.textColor"></label>${control("텍스트 크기", "content.textScale", .08, .7, .01)}${control("가로 위치", "content.x", 0, 1, .01)}${control("세로 위치", "content.y", 0, 1, .01)}</div><label class="select-row"><span>배경 색상</span><input aria-label="배경 색상" type="color" data-prism-bind="content.background"></label></section>
      <section class="studio-section"><header><h2>모션</h2><p>공유 꼭짓점을 유지하는 결정적 회전</p></header>${control("회전 속도", "motion.speed", .1, 3, .05)}${control("회전 강도", "motion.strength", 0, 1, .01)}<label class="toggle-row"><span>자동 회전</span><input aria-label="자동 회전" type="checkbox" data-prism-bind="motion.enabled"></label></section>
      <section class="studio-section prism-motion-kind"><label class="select-row"><span>모션 유형</span><select aria-label="Glass Prism 모션" data-prism-bind="motion.kind"><option value="rotate">회전</option><option value="shared-pulse">공유 꼭지점 맥동</option><option value="explode-rejoin">분해 후 결합</option></select></label></section>
      <details class="studio-section field-details"><summary>고급 설정</summary><div>${control("내부 반사", "material.internalBounces", 0, 6, 1)}${control("환경 강도", "environment.intensity", 0, 1.5, .01)}<label class="toggle-row"><span>환경 반사</span><input aria-label="환경 반사" type="checkbox" data-prism-bind="environment.enabled"></label>${control("큐브 크기", "geometry.scale", .5, 1.6, .01)}${control("큐브 간격", "geometry.gap", 0, .35, .005)}${control("카메라 좌우", "camera.yaw", -.8, .8, .005)}${control("카메라 상하", "camera.pitch", -.6, .6, .005)}</div></details>
      <section class="studio-section"><header><h2>아트보드</h2><p>미리보기와 출력이 같은 구도를 공유합니다</p></header><div class="dimension-grid"><label>W<input aria-label="아트보드 너비" type="number" data-prism-bind="artboard.width" min="16" max="8192" step="1"></label><label>H<input aria-label="아트보드 높이" type="number" data-prism-bind="artboard.height" min="16" max="8192" step="1"></label></div>${control("구조 크기", "artboard.scale", .25, 2, .01)}<label class="toggle-row"><span>투명 배경</span><input aria-label="투명 배경" type="checkbox" data-prism-bind="artboard.transparent"></label></section>
      <section class="studio-section" data-prism-output><header><h2>이미지 내보내기</h2><p>현재 프레임을 정확한 픽셀 크기로 저장</p></header><div class="export-summary"><span>PNG</span><b data-prism-output-size></b></div>${control("PPI", "export.ppi", 72, 600, 1)}<button class="wide-button primary" data-prism-export>PNG 내보내기</button><button class="wide-button" data-prism-sequence>시퀀스 명령 복사</button></section>
      </div></aside>`;
  }
}
