import type { DimentionR3FPresetId, DimentionR3FState } from "./DimentionR3FState";
import { resolveVideoDimensions } from "./DimentionR3FExportPipeline";

interface Actions { change(): void; preset(id: DimentionR3FPresetId): void; reset(): void; export(): Promise<void>; exportVideo(): void; cancelVideo(): void }
const control = (label: string, path: string, min: number, max: number, step: number) => `<div class="property-row"><label>${label}</label><input aria-label="${label}" type="range" data-r3f-bind="${path}" min="${min}" max="${max}" step="${step}"><input aria-label="${label} 값" type="number" data-r3f-bind="${path}" min="${min}" max="${max}" step="${step}"></div>`;
const toggle = (label: string, path: string) => `<label class="toggle-row"><span>${label}</span><input aria-label="${label}" type="checkbox" data-r3f-bind="${path}"></label>`;
const color = (label: string, path: string) => `<label class="color-property"><span>${label}</span><input aria-label="${label}" type="color" data-r3f-bind="${path}"></label>`;
const select = (label: string, path: string, options: ReadonlyArray<readonly [string, string]>) => `<label class="select-row"><span>${label}</span><select aria-label="${label}" data-r3f-bind="${path}">${options.map(([value, text]) => `<option value="${value}">${text}</option>`).join("")}</select></label>`;
const vector = (prefix: string, path: string, min = -12, max = 12, step = .1) => `${control(`${prefix} X`, `${path}.positionX`, min, max, step)}${control(`${prefix} Y`, `${path}.positionY`, min, max, step)}${control(`${prefix} Z`, `${path}.positionZ`, min, max, step)}`;
const lightDetails = (title: string, description: string, body: string, open = false) => `<details class="lighting-light-editor"${open ? " open" : ""}><summary><span><b>${title}</b><small>${description}</small></span></summary><div class="lighting-light-body">${body}</div></details>`;
const pathValue = (state: DimentionR3FState, path: string): unknown => path.split(".").reduce<unknown>((current, key) => (current as Record<string, unknown>)[key], state);
function setPath(state: DimentionR3FState, path: string, value: number | boolean | string): void { const keys = path.split("."); const target = keys.slice(0, -1).reduce<Record<string, unknown>>((current, key) => current[key] as Record<string, unknown>, state as unknown as Record<string, unknown>); target[keys.at(-1) as string] = value; }

export class DimentionR3FPanel {
  constructor(private readonly root: HTMLElement, private readonly state: DimentionR3FState, private readonly actions: Actions) { this.root.innerHTML = this.template(); this.bind(); this.sync(); }
  sync(): void {
    this.root.querySelectorAll<HTMLInputElement | HTMLSelectElement>("[data-r3f-bind]").forEach((input) => { const value = pathValue(this.state, input.dataset.r3fBind ?? ""); if (input instanceof HTMLInputElement && input.type === "checkbox") input.checked = Boolean(value); else input.value = String(value); });
    const preset = this.root.querySelector<HTMLSelectElement>("[data-r3f-preset]"); if (preset) preset.value = this.state.preset;
    const size = this.root.querySelector<HTMLElement>("[data-r3f-size]"); if (size) size.textContent = `${this.state.artboard.width} × ${this.state.artboard.height}px · ${this.state.export.ppi}ppi`;
    const fps = this.root.querySelector<HTMLSelectElement>("[data-r3f-video-fps]"); if (fps) fps.value = String(this.state.export.videoFps);
    const resolution = this.root.querySelector<HTMLSelectElement>("[data-r3f-video-resolution]"); if (resolution) resolution.value = this.state.export.videoResolution;
    const custom = this.root.querySelector<HTMLElement>("[data-r3f-video-custom]"); if (custom) custom.hidden = this.state.export.videoResolution !== "custom";
    const resolved = resolveVideoDimensions(this.state.artboard.width, this.state.artboard.height, this.state.export.videoResolution, this.state.export.videoWidth, this.state.export.videoHeight);
    const videoSize = this.root.querySelector<HTMLElement>("[data-r3f-video-size]"); if (videoSize) videoSize.textContent = `${resolved.width} × ${resolved.height}px`;
  }
  setVideoProgress(message: string, progress: number, busy: boolean): void {
    const status = this.root.querySelector<HTMLElement>("[data-r3f-video-status]");
    const meter = this.root.querySelector<HTMLElement>("[data-r3f-video-progress]");
    const start = this.root.querySelector<HTMLButtonElement>("[data-r3f-video-export]");
    const cancel = this.root.querySelector<HTMLButtonElement>("[data-r3f-video-cancel]");
    if (status) status.textContent = message;
    if (meter) { const percent = Math.round(Math.max(0, Math.min(1, progress)) * 100); meter.style.setProperty("--progress", `${percent}%`); meter.setAttribute("aria-valuenow", String(percent)); meter.setAttribute("aria-valuemin", "0"); meter.setAttribute("aria-valuemax", "100"); }
    if (start) { start.disabled = busy; start.setAttribute("aria-busy", String(busy)); start.textContent = busy ? "MP4 생성 중…" : "MP4 내보내기"; }
    if (cancel) cancel.hidden = !busy;
  }
  setImageProgress(message: string, busy: boolean): void {
    const status = this.root.querySelector<HTMLElement>("[data-r3f-image-status]");
    const button = this.root.querySelector<HTMLButtonElement>("[data-r3f-export]");
    if (status) status.textContent = message;
    if (button) { button.disabled = busy; button.setAttribute("aria-busy", String(busy)); button.textContent = busy ? "PNG 생성 중…" : "PNG 내보내기"; }
  }
  focusExport(): void { this.root.querySelector<HTMLElement>("[data-r3f-output]")?.scrollIntoView({ behavior: "smooth", block: "start" }); }
  private bind(): void {
    this.root.querySelector<HTMLSelectElement>("[data-r3f-preset]")?.addEventListener("change", (event) => this.actions.preset((event.currentTarget as HTMLSelectElement).value as DimentionR3FPresetId));
    this.root.querySelectorAll<HTMLInputElement | HTMLSelectElement>("[data-r3f-bind]").forEach((input) => input.addEventListener("input", (event) => {
      const target = event.currentTarget as HTMLInputElement | HTMLSelectElement;
      const path = target.dataset.r3fBind ?? "";
      const value = target instanceof HTMLSelectElement || target.type === "color" ? target.value : target.type === "checkbox" ? target.checked : Number(target.value);
      setPath(this.state, path, value);
      this.root.querySelectorAll<HTMLInputElement | HTMLSelectElement>(`[data-r3f-bind="${path}"]`).forEach((peer) => { if (peer !== target) { if (peer instanceof HTMLInputElement && peer.type === "checkbox") peer.checked = Boolean(value); else peer.value = String(value); } });
      this.actions.change();
    }));
    this.root.querySelector("[data-r3f-reset]")?.addEventListener("click", () => this.actions.reset());
    this.root.querySelector("[data-r3f-export]")?.addEventListener("click", () => { void this.actions.export(); });
    this.root.querySelector<HTMLSelectElement>("[data-r3f-video-fps]")?.addEventListener("change", (event) => { this.state.export.videoFps = Number((event.currentTarget as HTMLSelectElement).value) as 24 | 30 | 60; this.actions.change(); });
    this.root.querySelector<HTMLSelectElement>("[data-r3f-video-resolution]")?.addEventListener("change", (event) => { this.state.export.videoResolution = (event.currentTarget as HTMLSelectElement).value === "custom" ? "custom" : "4k"; this.actions.change(); });
    this.root.querySelector("[data-r3f-video-export]")?.addEventListener("click", () => this.actions.exportVideo());
    this.root.querySelector("[data-r3f-video-cancel]")?.addEventListener("click", () => this.actions.cancelVideo());
  }
  private template(): string {
    const spectralShapes = [["circle", "원형"], ["ellipse", "타원형"], ["ring", "링"]] as const;
    const environmentShapes = [["circle", "원형"], ["ellipse", "타원형"], ["ring", "링"], ["rect", "사각형"]] as const;
    const spectralEditor = (name: string, path: string) => lightDetails(name, "움직이는 브랜드 반사광", `${toggle(`${name} 사용`, `${path}.enabled`)}${select(`${name} 모양`, `${path}.shape`, spectralShapes)}${color(`${name} 색상`, `${path}.color`)}${control(`${name} 세기`, `${path}.intensity`, 0, 8, .01)}${vector(`${name} 중심`, path)}${control(`${name} 너비`, `${path}.width`, .05, 12, .05)}${control(`${name} 높이`, `${path}.height`, .05, 12, .05)}${control(`${name} 부드러움`, `${path}.softness`, .05, 1.5, .01)}${control(`${name} 회전 반경`, `${path}.orbitRadius`, 0, 12, .05)}${control(`${name} 수직 진폭`, `${path}.orbitHeight`, 0, 12, .05)}${control(`${name} 위상`, `${path}.phase`, -360, 360, 1)}`);
    const environmentEditor = (name: string, path: string) => lightDetails(name, "고정형 스튜디오 면광원", `${toggle(`${name} 사용`, `${path}.enabled`)}${select(`${name} 모양`, `${path}.shape`, environmentShapes)}${color(`${name} 색상`, `${path}.color`)}${control(`${name} 세기`, `${path}.intensity`, 0, 20, .05)}${vector(`${name} 위치`, path)}${control(`${name} 회전 X`, `${path}.rotationX`, -180, 180, 1)}${control(`${name} 회전 Y`, `${path}.rotationY`, -180, 180, 1)}${control(`${name} 회전 Z`, `${path}.rotationZ`, -180, 180, 1)}${control(`${name} 너비`, `${path}.width`, .05, 20, .05)}${control(`${name} 높이`, `${path}.height`, .05, 20, .05)}`);
    const keyEditor = lightDetails("화이트 키", "직접광 · 스팟 또는 사각 면광원", `${toggle("화이트 키 사용", "lighting.rig.key.enabled")}${select("화이트 키 모양", "lighting.rig.key.shape", [["spot", "스포트"], ["area", "사각 면광원"]])}${color("화이트 키 색상", "lighting.rig.key.color")}${control("화이트 키 세기", "lighting.rig.key.intensity", 0, 200, 1)}${vector("화이트 키 위치", "lighting.rig.key")}${control("화이트 키 목표 X", "lighting.rig.key.targetX", -6, 6, .1)}${control("화이트 키 목표 Y", "lighting.rig.key.targetY", -6, 6, .1)}${control("화이트 키 목표 Z", "lighting.rig.key.targetZ", -6, 6, .1)}${control("화이트 키 너비", "lighting.rig.key.width", .05, 20, .05)}${control("화이트 키 높이", "lighting.rig.key.height", .05, 20, .05)}${control("화이트 키 각도", "lighting.rig.key.angle", .05, 1.5, .01)}${control("화이트 키 페넘브라", "lighting.rig.key.penumbra", 0, 1, .01)}${control("화이트 키 거리", "lighting.rig.key.distance", 0, 50, .5)}${control("화이트 키 감쇠", "lighting.rig.key.decay", 0, 3, .05)}${control("화이트 키 이동량", "lighting.rig.key.motionAmount", 0, 6, .05)}`, true);
    return `<aside class="control-dock light-field-panel dimention-r3f-panel" data-mode-panel="dimention-r3f"><div class="inspector-header"><div><strong>DIMENTION R3F</strong><span>REALTIME OPTICAL GLASS</span></div></div><div class="inspector-views">
      <section class="studio-section"><header><h2>룩 프리셋</h2><p>실시간 유리와 조명 감도의 시작점</p></header><label class="select-row"><span>프리셋</span><select aria-label="Dimention R3F 프리셋" data-r3f-preset><option value="pleos-prism">PLEOS Prism</option><option value="clear-studio">Clear Studio</option><option value="dark-glass">Dark Glass</option></select></label><button class="wide-button" data-r3f-reset>기본값으로 초기화</button></section>
      <section class="studio-section"><header><h2>유리</h2><p>투과·분산·표면 반사를 실시간 계산합니다</p></header>${control("거칠기", "material.roughness", 0, .5, .005)}${control("투과", "material.transmission", 0, 1, .01)}${control("두께", "material.thickness", .05, 6, .05)}${control("IOR", "material.ior", 1.01, 2.333, .005)}${control("색 분산", "material.chromaticAberration", 0, .3, .002)}${control("비등방 블러", "material.anisotropicBlur", 0, .5, .005)}${control("흡수 거리", "material.attenuationDistance", .1, 20, .1)}${control("환경 반사", "material.environment", 0, 4, .05)}</section>
      <section class="studio-section"><header><h2>미러 디멘션</h2><p>바깥 유리 렌더를 재귀 샘플링해 육면체 반사상이 층층이 반복됩니다</p></header><label class="toggle-row"><span>내부 반사</span><input aria-label="내부 반사" type="checkbox" data-r3f-bind="mirror.enabled"></label>${control("반사 층수", "mirror.bounces", 1, 12, 1)}${control("재귀 축소율", "mirror.recursionScale", .5, .9, .01)}${control("반사 유지율", "mirror.reflectivity", .2, .98, .01)}${control("내부 흡수", "mirror.absorption", 0, 1.5, .01)}${control("내부 색 분산", "mirror.dispersion", 0, .2, .002)}${control("모서리 강조", "mirror.edgeIntensity", .2, 3, .02)}</section>
      <section class="studio-section dimention-lighting-rig"><header><h2>브랜드 조명</h2><p>광원을 선택해 모양·위치·크기·움직임을 개별 조정합니다</p></header>${control("전체 밝기", "lighting.master", 0, 3, .01)}${control("RGB 조명", "lighting.rgb", 0, 4, .01)}${control("화이트 조명", "lighting.white", 0, 4, .01)}${control("조명 속도", "lighting.speed", 0, 3, .01)}${control("노출", "lighting.exposure", .2, 3, .01)}${control("블룸", "lighting.bloom", 0, 1, .01)}${control("접촉 음영", "lighting.ao", 0, 4, .02)}${toggle("조명 모션", "motion.enabled")}<div class="lighting-rig-list">${keyEditor}${spectralEditor("레드 광원", "lighting.rig.red")}${spectralEditor("그린 광원", "lighting.rig.green")}${spectralEditor("블루 광원", "lighting.rig.blue")}${environmentEditor("화이트 면광원", "lighting.rig.whiteArea")}${environmentEditor("후면 광원", "lighting.rig.rear")}</div></section>
      <section class="studio-section"><header><h2>Axis 구조</h2><p>Glass 3D와 같은 보정 지오메트리</p></header>${control("큐브 갭", "geometry.gap", 0, .45, .005)}${control("베벨", "geometry.bevel", 0, .15, .0025)}${control("구조 크기", "artboard.scale", .25, 2, .01)}</section>
      <section class="studio-section"><header><h2>아트보드</h2><p>스튜디오 공통 판형과 배경을 유지합니다</p></header><div class="dimension-grid"><label>W<input aria-label="아트보드 너비" type="number" data-r3f-bind="artboard.width" min="16" max="8192" step="1"></label><label>H<input aria-label="아트보드 높이" type="number" data-r3f-bind="artboard.height" min="16" max="8192" step="1"></label></div><label class="color-row"><span>배경</span><input aria-label="배경 색상" type="color" data-r3f-bind="artboard.background"></label><label class="toggle-row"><span>투명 배경</span><input aria-label="투명 배경" type="checkbox" data-r3f-bind="artboard.transparent"></label></section>
      <details class="studio-section"><summary>실시간 품질</summary><div class="section-details">${control("재귀 버퍼 해상도", "quality.transmissionResolution", 128, 1024, 128)}${control("MSAA", "quality.multisampling", 0, 8, 1)}${control("최대 DPR", "quality.maxDpr", 1, 2, .1)}</div></details>
      <section class="studio-section" data-r3f-output><header><h2>이미지 내보내기</h2><p>최대 2× 슈퍼샘플링과 고해상도 광학 패스로 저장합니다</p></header><div class="export-summary"><span>PNG · 무손실</span><b data-r3f-size></b></div>${control("PPI", "export.ppi", 72, 600, 1)}<p class="export-help" data-r3f-image-status role="status" aria-live="polite">준비됨 · PNG 메타데이터와 안티앨리어싱 포함</p><button class="wide-button primary" data-r3f-export>PNG 내보내기</button></section>
      <section class="studio-section dimention-video-export"><header><h2>동영상 내보내기</h2><p>판형을 유지한 H.264 MP4를 프레임 단위로 렌더링합니다</p></header><label class="select-row"><span>출력 크기</span><select aria-label="동영상 해상도" data-r3f-video-resolution><option value="4k">4K · 현재 판형 유지</option><option value="custom">사용자 지정</option></select></label><div class="dimension-grid" data-r3f-video-custom hidden><label>W<input aria-label="동영상 너비" type="number" data-r3f-bind="export.videoWidth" min="16" max="8192" step="2"></label><label>H<input aria-label="동영상 높이" type="number" data-r3f-bind="export.videoHeight" min="16" max="8192" step="2"></label></div><div class="export-summary"><span>실제 출력</span><b data-r3f-video-size></b></div><label class="select-row"><span>프레임</span><select aria-label="동영상 FPS" data-r3f-video-fps><option value="24">24 fps</option><option value="30">30 fps</option><option value="60">60 fps</option></select></label>${control("비트레이트 Mbps", "export.videoBitrateMbps", 20, 160, 5)}<div class="dimention-video-meter" data-r3f-video-progress role="progressbar" aria-label="동영상 내보내기 진행률"><i></i></div><p class="export-help" data-r3f-video-status role="status" aria-live="polite">${this.state.motion.duration.toFixed(1)}초 전체 모션 · 디스크 스트리밍 우선</p><button class="wide-button primary" data-r3f-video-export>MP4 내보내기</button><button class="wide-button" data-r3f-video-cancel hidden>취소</button></section>
    </div></aside>`;
  }
}
