import { FormatPresetRegistry } from "../../artboard/FormatPresetRegistry";
import type { ArtboardState } from "../../artboard/ArtboardState";
import { MotionPresetRegistry } from "../../motion/MotionPresetRegistry";
import type { MotionSettings } from "../../motion/types";
import { CRYSTAL_LOOKS, type CrystalLook } from "../CrystalAssembly";
import type { InspectorTab } from "../InspectorPanel";
import type { SpectralFlowState } from "../materials/SpectralFlowMaterial";
import type { SoftSpectralState } from "../materials/SoftSpectralMaterial";
import { PRISM_STYLE_PRESETS, type PhysicalLookParameters, type PrismStyleId } from "../presets/PrismStylePresets";

export interface StudioPanelModel {
  look: CrystalLook; prismStyle: PrismStyleId; physical: PhysicalLookParameters;
  variations: Array<{ id: string; label: string; builtin: boolean }>; selectedVariationId: string;
  gap: number; bevelRadius: number; roughness: number; dispersion: number;
  reflection: number; refraction: number; exposure: number; bloom: number;
  saturation: number; environment: number; motion: MotionSettings;
  artboard: ArtboardState; activeTab: InspectorTab; outputSamples: number;
  bounces: number; renderScale: number; ppi: number;
  renderRegion: { enabled: boolean; x: number; y: number; width: number; height: number; unitPpi: number };
  printOutput: string; spectralFlow: SpectralFlowState; softSpectral: SoftSpectralState;
}

const property = (name: string, label: string, min: number, max: number, step: number, value: number): string =>
  `<div class="property-row"><label for="${name}-range">${label}</label><input id="${name}-range" data-control="${name}" type="range" min="${min}" max="${max}" step="${step}" value="${value}"><input data-number="${name}" data-scrub type="number" min="${min}" max="${max}" step="${step}" value="${value}" aria-label="${label} 값"></div>`;
const section = (title: string, content: string, subtitle = ""): string =>
  `<section class="studio-section"><header><h2>${title}</h2>${subtitle ? `<p>${subtitle}</p>` : ""}</header>${content}</section>`;
const advancedSection = (title: string, content: string, subtitle = ""): string =>
  `<details class="inspector-section"><summary><span><strong>${title}</strong>${subtitle ? `<small>${subtitle}</small>` : ""}</span><i></i></summary><div class="section-content">${content}</div></details>`;

const spectralDirection = (state: SpectralFlowState): string =>
  [["axis-30", "Axis 30°"], ["axis-90", "Axis 90°"], ["axis-150", "Axis 150°"], ["reverse", "Reverse"], ["auto", "Auto / Motion"]]
    .map(([value, label]) => `<option value="${value}" ${state.flowDirection === value ? "selected" : ""}>${label}</option>`).join("");

function spectralPrimary(state: SpectralFlowState, visible: boolean): string {
  return `<div class="spectral-flow-controls" data-spectral-flow-controls ${visible ? "" : "hidden"}>
    ${section("Style", `<div class="preset-cards spectral-preset-grid">${(["subtle", "balanced", "active"] as const).map((preset) => `<button data-spectral-preset="${preset}" class="${state.preset === preset ? "active" : ""}"><strong>${preset[0].toUpperCase() + preset.slice(1)}</strong><span>${preset === "subtle" ? "Dark & restrained" : preset === "balanced" ? "White core hero" : "Screen presence"}</span></button>`).join("")}</div>`)}
    ${section("Primary", `${property("spectral-flow-position", "Flow Position", -3, 3, .01, state.flowPosition)}<label class="select-row"><span>Flow Direction</span><select data-spectral-direction>${spectralDirection(state)}</select></label>${property("spectral-spread", "Spectrum", .1, 2.5, .01, state.spectrumSpread)}${property("spectral-core-intensity", "White Core", 0, 5, .01, state.coreIntensity)}${property("spectral-darkness", "Darkness", .1, 1, .01, state.darkness)}`)}
  </div>`;
}

function softSpectralPrimary(state: SoftSpectralState, visible: boolean): string {
  const descriptions = { subtle: "Quiet optical haze", balanced: "Soft spectral hero", active: "Expanded color field" } as const;
  return `<div class="spectral-flow-controls soft-spectral-controls" data-soft-spectral-controls ${visible ? "" : "hidden"}>
    ${section("Style", `<div class="preset-cards spectral-preset-grid">${(["subtle", "balanced", "active"] as const).map((preset) => `<button data-soft-spectral-preset="${preset}" class="${state.preset === preset ? "active" : ""}"><strong>${preset[0].toUpperCase() + preset.slice(1)}</strong><span>${descriptions[preset]}</span></button>`).join("")}</div>`)}
    ${section("Primary", `${property("soft-glow", "Glow", 0, 2.5, .01, state.glow)}${property("soft-spectrum", "Spectrum", 0, 2, .01, state.spectrum)}${property("soft-edge", "Edge", 0, 2, .01, state.edge)}${property("soft-darkness", "Darkness", .1, 1, .01, state.darkness)}${property("soft-motion-depth", "Motion Depth", 0, 1.5, .01, state.motionDepth)}`)}
    ${advancedSection("Optical Field", `${property("soft-center-radius", "Center Radius", .1, 2.5, .01, state.centerRadius)}${property("soft-center-softness", "Center Softness", .05, 1, .01, state.centerSoftness)}${property("soft-spread", "Spectrum Spread", .1, 2.5, .01, state.spectrumSpread)}${property("soft-separation", "Separation", 0, 1, .01, state.spectrumSeparation)}${property("soft-saturation", "Saturation", 0, 1.5, .01, state.saturation)}${property("soft-phase-offset", "Phase Offset", -1, 1, .01, state.phaseOffset)}${property("soft-edge-attraction", "Edge Attraction", 0, 2, .01, state.edgeAttraction)}${property("soft-edge-softness", "Edge Softness", .05, 1, .01, state.edgeSoftness)}${property("soft-reflection", "Reflection", 0, 3, .01, state.reflection)}${property("soft-roughness", "Roughness", .02, .5, .01, state.roughness)}${property("soft-falloff", "Falloff", .3, 4, .01, state.falloff)}${property("soft-bloom", "Bloom", 0, 1, .01, state.bloom)}`, "Soft Spectral only")}
  </div>`;
}

export function studioPanelTemplate(model: StudioPanelModel): string {
  const tabs: InspectorTab[] = ["setup", "look", "motion", "format", "export"];
  const motionOptions = MotionPresetRegistry.list().map((preset) => `<option value="${preset.id}" ${model.motion.preset === preset.id ? "selected" : ""}>${preset.label}</option>`).join("");
  const formatOptions = FormatPresetRegistry.list().map((preset) => `<option value="${preset.id}" ${model.artboard.id === preset.id ? "selected" : ""}>${preset.label}</option>`).join("");
  const styleCards = Object.values(PRISM_STYLE_PRESETS).map((preset) => `<button data-prism-style="${preset.id}" class="${model.prismStyle === preset.id ? "active" : ""}"><strong>${preset.label}</strong><span>${preset.description}</span></button>`).join("");
  const variationOptions = `<option value="" ${model.selectedVariationId ? "" : "selected"}>현재 설정</option>` + model.variations.map((item) => `<option value="${item.id}" ${item.id === model.selectedVariationId ? "selected" : ""}>${item.label}${item.builtin ? "" : " · User"}</option>`).join("");
  const formatButtons = FormatPresetRegistry.list().filter((item) => item.id !== "custom").map((item) => `<button data-format-preset="${item.id}" class="${model.artboard.id === item.id ? "active" : ""}">${item.shortLabel}</button>`).join("");
  return `<button class="inspector-toggle" data-action="inspector-toggle" aria-label="Inspector 표시 또는 숨기기"><span></span><span></span></button>
    <aside class="control-dock" aria-label="Pleos Axis Inspector">
      <header class="inspector-header"><div><strong>Pleos Axis</strong><span data-output="save">자동 저장</span></div><button data-action="advanced-toggle">고급</button><button data-action="inspector-close">×</button></header>
      <div class="variation-bar"><label><span>Variation</span><select data-variation>${variationOptions}</select></label><div><button data-action="variation-save" class="primary">+ 저장</button><button data-action="variation-duplicate" title="복제">⧉</button><button data-action="variation-rename" title="이름 변경">✎</button><button data-action="variation-delete" title="삭제">×</button></div></div>
      <nav class="inspector-tabs" role="tablist">${tabs.map((tab) => `<button role="tab" data-inspector-tab="${tab}" class="${model.activeTab === tab ? "active" : ""}">${tab.toUpperCase()}</button>`).join("")}</nav>
      <div class="inspector-views">
        <div class="inspector-view" data-inspector-view="setup">${section("Axis", `<div class="axis-status"><span>Family</span><b>30°</b><span>Origin</span><b>Shared</b><span>Vertex</span><b data-output="vertex-status">Valid</b></div>`, "브랜드 구조는 잠겨 있고 표현만 조정됩니다.")}${section("Model", `${property("gap", "Cube Gap", 0, .45, .01, model.gap)}${property("bevel-radius", "Bevel", 0, .15, .001, model.bevelRadius)}`)}${section("View", `<div class="button-grid"><button data-action="reset">카메라 초기화</button><button data-action="scene-reset">장면 초기화</button></div><label class="toggle-row">시점 잠금<input data-control="view-lock" type="checkbox" checked></label>`)}</div>
        <div class="inspector-view" data-inspector-view="look">
          ${section("Expression", `<div class="segmented look-segmented">${CRYSTAL_LOOKS.map((look) => `<button data-look="${look}" class="${model.look === look ? "active" : ""}">${look === "spectral-flow" ? "Spectral" : look[0].toUpperCase() + look.slice(1)}</button>`).join("")}</div>`)}
          <div data-physical-optics ${model.look === "spectral-flow" ? "hidden" : ""}><div data-prism-style-panel ${model.look === "prism" ? "" : "hidden"}>${section("Style", `<div class="preset-cards">${styleCards}</div>`)}</div>${section("Primary", `${property("roughness", "Roughness", .02, .28, .01, model.roughness)}${property("dispersion", "Dispersion", 0, .35, .01, model.dispersion)}${property("reflection-strength", "Reflection", 0, 3, .05, model.reflection)}${property("refraction-strength", "Refraction", 0, 1.25, .01, model.refraction)}${property("master-intensity", "Light Intensity", 0, 3, .05, 1)}`)}</div>
          ${spectralPrimary(model.spectralFlow, model.look === "spectral-flow")}<button class="advanced-link" data-action="advanced-toggle">Advanced Look →</button>
        </div>
        <div class="inspector-view" data-inspector-view="motion">${section("Motion", `<label class="toggle-row primary-toggle">Motion<input data-motion="enabled" type="checkbox" ${model.motion.enabled ? "checked" : ""}></label><label class="select-row"><span>Preset</span><select data-motion="preset"><option value="off">Off</option>${motionOptions}</select></label><label class="select-row"><span>Character</span><select data-motion="strength-mode"><option value="restrained">Restrained</option><option value="balanced" ${model.motion.strengthMode === "balanced" ? "selected" : ""}>Balanced</option><option value="active">Active</option></select></label>${property("motion-strength", "Intensity", 0, 1, .01, model.motion.strength)}${property("motion-duration", "Duration", 1, 12, .1, model.motion.duration)}<label class="toggle-row">Loop<input data-motion="loop" type="checkbox" ${model.motion.loop ? "checked" : ""}></label><button class="wide-button" data-action="motion-reset">Reset Motion</button>`)}<button class="advanced-link" data-action="advanced-toggle">Advanced Motion →</button></div>
        <div class="inspector-view" data-inspector-view="format">${section("Preset", `<div class="format-segmented">${formatButtons}</div>`)}${section("Composition", `${property("artboard-scale", "Scale", .25, 2, .01, model.artboard.scale)}${property("axis-anchor-x", "Axis X", 0, 1, .01, model.artboard.axisAnchor.gridX)}${property("axis-anchor-y", "Axis Y", 0, 1, .01, model.artboard.axisAnchor.gridY)}<label class="color-property"><span>Background</span><input data-format="background" type="color" value="${model.artboard.background}"></label><label class="toggle-row">Transparency<input data-format="transparent" type="checkbox" ${model.artboard.transparent ? "checked" : ""}></label>`)}<button class="advanced-link" data-action="advanced-toggle">Advanced Format →</button></div>
        <div class="inspector-view" data-inspector-view="export">${section("Still", `<button class="wide-button" data-action="export-raster">Raster PNG</button><button class="wide-button primary" data-action="render-current-high">Path Traced PNG</button>`)}${section("Motion", `<button class="wide-button" data-action="copy-sequence">PNG Sequence 명령 복사</button><code data-output="sequence-command" hidden></code>`)}${section("Output", `<div class="export-summary"><span>Pixel dimensions</span><b data-output="export-size">${model.artboard.width} × ${model.artboard.height}px</b></div>`)}<button class="advanced-link" data-action="advanced-toggle">Advanced Export →</button></div>
      </div>
      <div class="advanced-drawer" data-advanced hidden><header><div><strong>Advanced</strong><span>Technical controls</span></div><button data-action="advanced-close">×</button></header>
        ${advancedSection("Physical Glass", `${property("ior", "IOR", 1, 2.5, .001, model.physical.ior)}${property("thickness", "Thickness", .01, 10, .01, model.physical.thickness)}${property("attenuation-distance", "Attenuation", .1, 20, .1, model.physical.attenuationDistance)}${property("iridescence", "Iridescence", 0, 1, .01, model.physical.iridescence)}${property("environment-intensity", "Environment", 0, 3, .05, model.environment)}${property("exposure", "Exposure", .2, 2.5, .05, model.exposure)}${property("bloom-intensity", "Bloom", 0, 1.5, .05, model.bloom)}${property("color-saturation", "Saturation", 0, 2, .05, model.saturation)}`)}
        ${advancedSection("Spectral Flow", `${property("spectral-flow-speed", "Speed", 0, 3, .01, model.spectralFlow.flowSpeed)}${property("spectral-flow-width", "Width", .08, 2.4, .01, model.spectralFlow.flowWidth)}${property("spectral-flow-softness", "Softness", .05, 1, .01, model.spectralFlow.flowSoftness)}${property("spectral-separation", "Separation", 0, 1.4, .01, model.spectralFlow.spectrumSeparation)}${property("spectral-saturation", "Saturation", 0, 2, .01, model.spectralFlow.saturation)}${property("spectral-lag", "Spectral Lag", 0, .75, .01, model.spectralFlow.spectralLag)}${property("spectral-core-width", "Core Width", .02, .8, .01, model.spectralFlow.coreWidth)}${property("spectral-falloff", "Falloff", .25, 4, .01, model.spectralFlow.falloff)}${property("spectral-bloom", "Bloom", 0, 1.5, .01, model.spectralFlow.bloom)}${property("spectral-edge-attraction", "Edge Attraction", 0, 2.5, .01, model.spectralFlow.edgeAttraction)}${property("spectral-reflection", "Reflection", 0, 3, .01, model.spectralFlow.reflection)}`)}
        ${advancedSection("Motion Technical", `${property("motion-fps", "FPS", 12, 60, 1, model.motion.fps)}<div data-motion-parameters></div>`)}
        ${advancedSection("Format Technical", `<label class="select-row"><span>Format</span><select data-format="preset">${formatOptions}</select></label><div class="dimension-grid"><label>W<input data-format="width" type="number" value="${model.artboard.width}"></label><label>H<input data-format="height" type="number" value="${model.artboard.height}"></label></div><label class="select-row"><span>Fit</span><select data-format="fit"><option value="contain">Contain</option><option value="cover">Cover</option><option value="custom">Custom</option></select></label>${property("preview-zoom", "Preview Zoom", .5, 1.8, .05, model.artboard.previewZoom)}<label class="toggle-row">Safe guide<input data-format="safe-guide" type="checkbox" ${model.artboard.safeGuide ? "checked" : ""}></label>`)}
        ${advancedSection("Path Tracing", `<div class="render-quality-grid"><button data-action="render-fast"><strong>Fast Preview</strong><span>16 spp</span></button><button data-action="render-high"><strong>High Quality</strong><span>${model.outputSamples} spp</span></button></div>${property("scale", "Render Scale", .4, 1, .05, model.renderScale)}${property("bounces", "Bounces", 3, 14, 1, model.bounces)}${property("target-samples", "Samples", 16, 512, 16, model.outputSamples)}`)}
        ${advancedSection("Render Region", `<label class="toggle-row primary-toggle">부분 렌더링<input data-region-enabled type="checkbox" ${model.renderRegion.enabled ? "checked" : ""}></label><div class="render-region-actions"><button data-action="region-center">가운데</button><button data-action="region-full">전체</button></div><label class="select-row"><span>단위 기준</span><span class="unit-value"><input data-unit-ppi data-scrub type="number" min="36" max="1200" value="${model.renderRegion.unitPpi}"><i>ppi</i></span></label><div class="motion-region-grid">${([['x','X',model.renderRegion.x],['y','Y',model.renderRegion.y],['width','W',model.renderRegion.width],['height','H',model.renderRegion.height]] as const).map(([key,label,value]) => `<label><span>${label}</span><input data-region="${key}" type="text" value="${value}"><i>px</i></label>`).join("")}</div>`)}
        ${advancedSection("Print Output", `<label class="select-row"><span>Output PPI</span><select data-control="export-ppi">${[72,150,300].map((ppi) => `<option value="${ppi}" ${model.ppi === ppi ? "selected" : ""}>${ppi}</option>`).join("")}</select></label><div class="export-summary"><span>Physical-size output</span><b data-output="print-size">${model.printOutput}</b></div><button class="wide-button primary" data-action="export-print">PPI 기준 렌더·저장</button>`)}
        ${advancedSection("Individual Lights", `<section class="lighting-panel" data-lighting-panel></section>`)}
      </div>
      ${softSpectralPrimary(model.softSpectral, model.look === "soft-spectral")}
    </aside>`;
}
