import type { AxisMegastructurePresetId, AxisMegastructureState } from "./AxisMegastructureState";

export interface AxisMegastructurePanelMetrics { phase?: string; fps?: number; drawCalls?: number; macro?: number; panel?: number; greeble?: number; circuit?: number }
interface PanelCallbacks {
  change(path: string, expensive: boolean): void; regenerate(): void; preset(id: AxisMegastructurePresetId): void;
  focusAxis(): void;
  randomize(scope: "all" | "geometry" | "lighting" | "motion"): void; transport(action: "play" | "pause" | "restart"): void;
  savePreset(name: string): void; loadPreset(id: string): void; duplicatePreset(id: string): void; deletePreset(id: string): void;
  listPresets(): Array<{ id: string; name: string }>; export(): void;
}

function getValue(state: AxisMegastructureState, path: string): unknown { return path.split(".").reduce<unknown>((value, key) => value && typeof value === "object" ? (value as Record<string, unknown>)[key] : undefined, state); }
function setValue(state: AxisMegastructureState, path: string, value: unknown): void { const keys = path.split("."); let target = state as unknown as Record<string, unknown>; keys.slice(0, -1).forEach((key) => { target = target[key] as Record<string, unknown>; }); target[keys[keys.length - 1]] = value; }
function numberControl(state: AxisMegastructureState, path: string, label: string, min: number, max: number, step: number, expensive = false): string { const value = Number(getValue(state, path)); return `<div class="property-row mega-property"><label for="mega-${path}">${label}</label><input id="mega-${path}" type="range" min="${min}" max="${max}" step="${step}" value="${value}" data-mega-path="${path}" data-mega-expensive="${expensive}"><input type="number" min="${min}" max="${max}" step="${step}" value="${value}" aria-label="${label} 값" data-mega-path="${path}" data-mega-expensive="${expensive}"></div>`; }
function toggleControl(state: AxisMegastructureState, path: string, label: string, expensive = false): string { return `<label class="toggle-row"><span>${label}</span><input type="checkbox" ${getValue(state, path) ? "checked" : ""} aria-label="${label}" data-mega-path="${path}" data-mega-expensive="${expensive}"></label>`; }
function group(title: string, subtitle: string, content: string, open = false): string { return `<details class="mega-control-group" ${open ? "open" : ""}><summary><span><strong>${title}</strong><small>${subtitle}</small></span><i aria-hidden="true">⌄</i></summary><div>${content}</div></details>`; }

export class AxisMegastructurePanel {
  private metrics: AxisMegastructurePanelMetrics = {};
  private busy = false;
  private pending = false;
  constructor(private readonly host: HTMLElement, private readonly state: AxisMegastructureState, private readonly callbacks: PanelCallbacks) { this.render(); }
  dispose(): void { this.host.replaceChildren(); }
  focusExport(): void { this.host.querySelector<HTMLElement>("[data-mega-export]")?.scrollIntoView({ behavior: "smooth", block: "center" }); }
  setBusy(value: boolean): void { this.busy = value; if (!value) this.pending = false; this.sync(); }
  markPending(): void { this.pending = true; this.sync(); }
  sync(metrics?: AxisMegastructurePanelMetrics): void {
    if (metrics) this.metrics = { ...this.metrics, ...metrics };
    const phase = this.host.querySelector<HTMLElement>("[data-mega-phase]"); if (phase) phase.textContent = this.busy ? "REBUILDING WORLD" : this.metrics.phase ?? "MONOLITH";
    const performance = this.host.querySelector<HTMLElement>("[data-mega-metrics]"); if (performance) performance.textContent = `${Math.round(this.metrics.fps ?? 0)} FPS · ${this.metrics.drawCalls ?? 0} CALLS`;
    const hierarchy = this.host.querySelector<HTMLElement>("[data-mega-hierarchy]"); if (hierarchy) hierarchy.textContent = `${this.metrics.macro ?? 0} / ${this.metrics.panel ?? 0} / ${this.metrics.greeble ?? 0} / ${this.metrics.circuit ?? 0}`;
    this.host.querySelectorAll<HTMLButtonElement>("[data-mega-regenerate]").forEach((button) => { button.disabled = this.busy; button.textContent = this.busy ? "연속 구조 생성 중…" : this.pending ? "변경 사항으로 세계 재생성" : "연속 구조 재생성"; button.classList.toggle("pending", this.pending); });
  }

  private render(): void {
    const state = this.state; const saved = this.callbacks.listPresets(); const savedOptions = saved.length ? saved.map((item) => `<option value="${item.id}">${item.name}</option>`).join("") : `<option value="">저장된 프리셋 없음</option>`;
    this.host.innerHTML = `<aside class="control-dock mega-panel" aria-label="Axis Megastructure 제어 패널">
      <header class="inspector-header mega-panel-header"><div><strong>AXIS MEGASTRUCTURE</strong><span>CONTINUOUS WORLD · ULTRA</span></div></header>
      <div class="mega-panel-scroll">
        <section class="mega-status" aria-live="polite"><div><span class="mega-live-dot"></span><strong data-mega-phase>MONOLITH</strong><small data-mega-metrics>0 FPS · 0 CALLS</small></div><p>연속 매스의 표면이 AXIS 전파에 따라 분할되고 내부 회로까지 해상됩니다.</p><dl><div><dt>MASS / PANEL / GREEBLE / CIRCUIT</dt><dd data-mega-hierarchy>0 / 0 / 0 / 0</dd></div><div><dt>SEED</dt><dd>${state.seed}</dd></div></dl></section>
        <section class="studio-section mega-primary-actions"><label class="select-row"><span>기본 프리셋</span><select aria-label="Axis Megastructure 프리셋" data-mega-preset><option value="abyssal-core" ${state.preset === "abyssal-core" ? "selected" : ""}>Abyssal Core</option><option value="violet-foundry" ${state.preset === "violet-foundry" ? "selected" : ""}>Violet Foundry</option><option value="cold-archive" ${state.preset === "cold-archive" ? "selected" : ""}>Cold Archive</option></select></label><button class="wide-button primary mega-regenerate" data-mega-regenerate>연속 구조 재생성</button><div class="button-grid mega-transport"><button data-mega-transport="play">재생</button><button data-mega-transport="pause">정지</button><button data-mega-transport="restart">처음부터</button><button data-mega-random="all">전체 변형</button></div></section>
        ${group("AXIS", "거대한 연속 계산 백본", [
          numberControl(state,"axis.positionX","위치 X",-8,8,.05,true),numberControl(state,"axis.positionY","위치 Y",-8,8,.05,true),numberControl(state,"axis.positionZ","위치 Z",-140,20,.5,true),numberControl(state,"axis.rotationX","회전 X",-20,20,.25,true),numberControl(state,"axis.rotationY","회전 Y",-20,20,.25,true),numberControl(state,"axis.rotationZ","회전 Z",-20,20,.25,true),
          numberControl(state,"axis.length","길이",80,280,1,true),numberControl(state,"axis.width","폭",.8,7,.05,true),numberControl(state,"axis.depth","깊이",.6,6,.05,true),numberControl(state,"axis.visualMass","시각 질량",.5,1.8,.01,true),numberControl(state,"axis.channelCount","채널 수",1,12,1,true),numberControl(state,"axis.channelSpacing","채널 간격",.05,.7,.01,true),numberControl(state,"axis.surfaceComplexity","표면 복잡도",0,1,.01),numberControl(state,"axis.emission","발광",0,6,.05),numberControl(state,"axis.localIllumination","국소 조명",0,1.5,.01),numberControl(state,"axis.visibilityHierarchy","가독성 위계",0,1.5,.01),`<button class="wide-button" data-mega-focus-axis>AXIS 중심 구도 적용</button>`
        ].join(""),true)}
        ${group("CAMERA", "구조 협곡 내부의 강한 원근", [
          numberControl(state,"camera.positionX","위치 X",-12,12,.05),numberControl(state,"camera.positionY","위치 Y",-10,12,.05),numberControl(state,"camera.positionZ","위치 Z",-30,32,.1),numberControl(state,"camera.targetX","타깃 X",-8,8,.05),numberControl(state,"camera.targetY","타깃 Y",-8,8,.05),numberControl(state,"camera.targetZ","타깃 Z",-220,-10,1),numberControl(state,"camera.fov","FOV",48,88,.5),numberControl(state,"camera.roll","롤",-8,8,.05),numberControl(state,"camera.near","니어",.01,2,.01),numberControl(state,"camera.far","파",120,600,5),numberControl(state,"camera.drift","드리프트",0,.8,.01),numberControl(state,"camera.motionSpeed","이동 속도",0,1,.01),numberControl(state,"camera.parallax","패럴랙스",0,.8,.01)
        ].join(""))}
        ${group("MACRO STRUCTURE", "화면 밖까지 이어지는 연결 매스", [
          numberControl(state,"seed","결정 시드",1,999999,1,true),numberControl(state,"macro.density","구조 밀도",.4,1,.01,true),numberControl(state,"macro.wallProximity","벽 근접도",.5,1.35,.01,true),numberControl(state,"macro.leftMass","좌측 질량",.35,1.5,.01,true),numberControl(state,"macro.rightMass","우측 질량",.35,1.5,.01,true),numberControl(state,"macro.upperMass","상부 질량",.3,1.5,.01,true),numberControl(state,"macro.foregroundMass","전경 질량",.4,1.6,.01,true),numberControl(state,"macro.macroScale","매크로 크기",.65,1.5,.01,true),numberControl(state,"macro.macroDepth","깊이 길이",.6,1.6,.01,true),numberControl(state,"macro.canyonWidth","협곡 폭",.45,1.4,.01,true),numberControl(state,"macro.irregularity","구조 불규칙",0,1,.01,true),numberControl(state,"macro.voidAmount","보이드",0,.25,.005,true),`<button class="wide-button" data-mega-random="geometry">구조만 변형</button>`
        ].join(""))}
        ${group("SUBDIVISION", "비균일 재귀 표면 분할", [
          toggleControl(state,"subdivision.enabled","재귀 분할",true),numberControl(state,"subdivision.depth","재귀 깊이",1,7,1,true),numberControl(state,"subdivision.probability","분할 확률",.2,1,.01,true),numberControl(state,"subdivision.minCellSize","최소 셀",.03,.8,.01,true),numberControl(state,"subdivision.maxCellSize","최대 셀",.3,2,.01,true),numberControl(state,"subdivision.horizontalProbability","가로 분할",0,1,.01,true),numberControl(state,"subdivision.verticalProbability","세로 분할",0,1,.01,true),numberControl(state,"subdivision.irregularity","비균일 비율",0,1,.01,true),numberControl(state,"subdivision.inset","인셋",0,.15,.002,true),numberControl(state,"subdivision.gap","간격",0,.16,.002,true),numberControl(state,"subdivision.localDensityVariation","국소 밀도 변화",0,1,.01,true)
        ].join(""))}
        ${group("PANELS", "분할 셀의 돌출과 함몰", [
          numberControl(state,"panels.extrusionProbability","돌출 확률",0,1,.01,true),numberControl(state,"panels.extrusionMin","최소 돌출",0,.5,.01,true),numberControl(state,"panels.extrusionMax","최대 돌출",.05,1.5,.01,true),numberControl(state,"panels.recessProbability","함몰 확률",0,1,.01,true),numberControl(state,"panels.recessMin","최소 함몰",0,.5,.01,true),numberControl(state,"panels.recessMax","최대 함몰",.05,1.2,.01,true),numberControl(state,"panels.density","패널 밀도",.2,1,.01,true),numberControl(state,"panels.thickness","패널 두께",.02,.5,.01,true),numberControl(state,"panels.scaleVariation","크기 변화",0,1,.01,true),numberControl(state,"panels.depthVariation","깊이 변화",0,1.5,.01,true)
        ].join(""))}
        ${group("GREEBLE", "표면에 고정된 물리 디테일", [
          toggleControl(state,"greeble.enabled","그리블",true),numberControl(state,"greeble.density","밀도",0,1,.01,true),numberControl(state,"greeble.minScale","최소 크기",.01,.2,.005,true),numberControl(state,"greeble.maxScale","최대 크기",.05,.8,.01,true),numberControl(state,"greeble.height","높이",.02,1,.01,true),numberControl(state,"greeble.recessProbability","함몰 확률",0,1,.01,true),numberControl(state,"greeble.repetition","반복성",0,1,.01,true),numberControl(state,"greeble.irregularity","불규칙성",0,1,.01,true),numberControl(state,"greeble.orientationBias","방향 편향",0,1,.01,true)
        ].join(""))}
        ${group("MICRO CIRCUITS", "5주파수 셰이더 회로", [
          toggleControl(state,"micro.enabled","마이크로 회로"),numberControl(state,"micro.density","전체 밀도",0,1,.01),numberControl(state,"micro.frequency1","주파수 1",.2,4,.05),numberControl(state,"micro.frequency2","주파수 2",1,12,.1),numberControl(state,"micro.frequency3","주파수 3",4,28,.5),numberControl(state,"micro.frequency4","주파수 4",12,72,1),numberControl(state,"micro.frequency5","주파수 5",30,180,1),numberControl(state,"micro.lineThickness","선 두께",.008,.12,.002),numberControl(state,"micro.pathComplexity","경로 복잡도",0,1,.01),numberControl(state,"micro.pathInterruption","경로 단절",0,1,.01),numberControl(state,"micro.branching","분기",0,1,.01),numberControl(state,"micro.nodeProbability","노드 확률",0,.2,.002),numberControl(state,"micro.brightness","밝기",0,10,.05),numberControl(state,"micro.emissivePercentage","발광 비율",0,.5,.005),numberControl(state,"micro.cyanPercentage","시안 비율",0,.3,.005),numberControl(state,"micro.magentaPercentage","마젠타 비율",0,.5,.005),numberControl(state,"micro.surfaceContrast","표면 대비",0,1.5,.01)
        ].join(""))}
        ${group("MATERIAL", "물리적으로 풍부한 근흑색", [
          numberControl(state,"material.baseDarkness","기본 암도",.7,1,.005),numberControl(state,"material.roughness","거칠기",0,1,.01),numberControl(state,"material.roughnessVariation","거칠기 변화",0,1,.01),numberControl(state,"material.metalness","금속성",0,1,.01),numberControl(state,"material.specular","스페큘러",0,1.5,.01),numberControl(state,"material.reflectionStrength","반사 강도",0,3,.01),numberControl(state,"material.normalStrength","노멀 강도",0,1.5,.01),numberControl(state,"material.surfaceMicroVariation","미세 표면 변화",0,1,.01)
        ].join(""))}
        ${group("LIGHTING", "내부광·사광·가짜 간접광", [
          numberControl(state,"lighting.exposure","노출",.2,2,.01),numberControl(state,"lighting.ambientIntensity","앰비언트",0,.8,.01),numberControl(state,"lighting.magentaInternal","마젠타 내부광",0,10,.05),numberControl(state,"lighting.violetInternal","바이올렛 내부광",0,10,.05),numberControl(state,"lighting.coolHighlight","쿨 하이라이트",0,10,.05),numberControl(state,"lighting.rimStrength","림 강도",0,12,.05),numberControl(state,"lighting.bounceStrength","바운스",0,1.5,.01),numberControl(state,"lighting.cavityIllumination","캐비티 조명",0,1.5,.01),numberControl(state,"lighting.lightFalloff","감쇠",.2,3,.01),`<button class="wide-button" data-mega-random="lighting">조명만 변형</button>`
        ].join(""))}
        ${group("BLOOM + AO", "블룸이 꺼져도 유지되는 구조", [
          toggleControl(state,"bloom.enabled","블룸"),numberControl(state,"bloom.threshold","임계",.4,2.5,.01),numberControl(state,"bloom.strength","강도",0,1.2,.01),numberControl(state,"bloom.radius","반경",0,.8,.01),numberControl(state,"bloom.softKnee","소프트 니",0,1,.01),toggleControl(state,"ao.enabled","GTAO"),numberControl(state,"ao.intensity","AO 강도",0,3,.01),numberControl(state,"ao.radius","AO 반경",.02,2,.01),numberControl(state,"ao.distanceFalloff","거리 감쇠",.1,3,.01),numberControl(state,"ao.cavityStrength","캐비티 강도",0,2,.01)
        ].join(""))}
        ${group("ATMOSPHERE", "먼 구조가 암부로 압축되는 깊이", [
          toggleControl(state,"atmosphere.fogEnabled","안개"),numberControl(state,"atmosphere.fogDensity","안개 밀도",0,.04,.0005),numberControl(state,"atmosphere.fogStart","안개 시작",0,100,1),numberControl(state,"atmosphere.fogFalloff","안개 감쇠",.2,3,.01),numberControl(state,"atmosphere.fogDarkness","안개 암도",0,1,.01),numberControl(state,"atmosphere.violetContribution","바이올렛 기여",0,1,.01),numberControl(state,"atmosphere.distanceContrast","거리 대비",0,1.5,.01)
        ].join(""))}
        ${group("AXIS GENERATION", "기존 표면을 복잡도로 해상", [
          toggleControl(state,"generation.enabled","생성 모션"),numberControl(state,"generation.radius","영향 반경",2,40,.1),numberControl(state,"generation.influenceFalloff","영향 감쇠",0,1.5,.01),numberControl(state,"generation.activationSpeed","활성 속도",.2,2,.01),numberControl(state,"generation.activationFrequency","활성 빈도",.2,2,.01),numberControl(state,"generation.propagationSpeed","전파 속도",.1,2,.01),numberControl(state,"generation.recursionResponse","분할 반응",0,1.5,.01),numberControl(state,"generation.panelResponse","패널 반응",0,1.5,.01),numberControl(state,"generation.greebleResponse","그리블 반응",0,1.5,.01),numberControl(state,"generation.circuitResponse","회로 반응",0,1.5,.01),numberControl(state,"generation.emissionResponse","발광 반응",0,1.5,.01),numberControl(state,"generation.stagger","시차",0,1,.01),numberControl(state,"generation.randomness","시간 불규칙",0,1,.01),toggleControl(state,"generation.loopEnabled","루프"),numberControl(state,"generation.duration","루프 길이",6,40,.5),toggleControl(state,"generation.debugInfluence","영향 필드 디버그"),`<button class="wide-button" data-mega-random="motion">모션만 변형</button>`
        ].join(""))}
        ${group("QUALITY + PRESETS", "Ultra 기준 데스크톱 출력", `
          <label class="select-row"><span>품질</span><select aria-label="렌더 품질" data-mega-path="performance.quality" data-mega-expensive="true"><option value="low" ${state.performance.quality === "low" ? "selected" : ""}>Low</option><option value="medium" ${state.performance.quality === "medium" ? "selected" : ""}>Medium</option><option value="high" ${state.performance.quality === "high" ? "selected" : ""}>High</option><option value="ultra" ${state.performance.quality === "ultra" ? "selected" : ""}>Ultra</option></select></label>${toggleControl(state,"performance.postprocessing","후처리")}<label class="mega-name-row"><span>이름</span><input type="text" value="My Continuous World" maxlength="40" data-mega-preset-name aria-label="저장할 프리셋 이름"></label><button class="wide-button" data-mega-save>현재 설정 저장</button><label class="select-row"><span>저장 목록</span><select aria-label="저장된 프리셋" data-mega-saved>${savedOptions}</select></label><div class="button-grid"><button data-mega-load>불러오기</button><button data-mega-duplicate>복제</button><button data-mega-delete>삭제</button><button data-mega-random="all">무작위</button></div>
        `)}
        ${group("EXPORT", "현재 프레임 PNG", `<div class="export-summary"><span>PNG · ACES · ${state.export.ppi} PPI</span><b>${state.artboard.width} × ${state.artboard.height}px</b></div>${numberControl(state,"export.ppi","PPI",72,600,1)}<button class="wide-button primary" data-mega-export>PNG 내보내기</button>`)}
      </div></aside>`;
    this.bind(); this.sync();
  }

  private bind(): void {
    this.host.querySelectorAll<HTMLInputElement | HTMLSelectElement>("[data-mega-path]").forEach((control) => { const eventName = control instanceof HTMLInputElement && control.type === "range" ? "input" : "change"; control.addEventListener(eventName, () => { const path = control.dataset.megaPath; if (!path) return; const value = control instanceof HTMLInputElement && control.type === "checkbox" ? control.checked : control instanceof HTMLInputElement && (control.type === "range" || control.type === "number") ? Number(control.value) : control.value; setValue(this.state, path, value); const expensive = control.dataset.megaExpensive === "true"; this.syncLinked(path, value); if (expensive) this.markPending(); this.callbacks.change(path, expensive); }); });
    this.host.querySelector<HTMLSelectElement>("[data-mega-preset]")?.addEventListener("change", (event) => this.callbacks.preset((event.currentTarget as HTMLSelectElement).value as AxisMegastructurePresetId));
    this.host.querySelectorAll<HTMLButtonElement>("[data-mega-regenerate]").forEach((button) => button.addEventListener("click", () => this.callbacks.regenerate()));
    this.host.querySelector<HTMLButtonElement>("[data-mega-focus-axis]")?.addEventListener("click", () => this.callbacks.focusAxis());
    this.host.querySelectorAll<HTMLButtonElement>("[data-mega-random]").forEach((button) => button.addEventListener("click", () => this.callbacks.randomize(button.dataset.megaRandom as "all" | "geometry" | "lighting" | "motion")));
    this.host.querySelectorAll<HTMLButtonElement>("[data-mega-transport]").forEach((button) => button.addEventListener("click", () => this.callbacks.transport(button.dataset.megaTransport as "play" | "pause" | "restart")));
    this.host.querySelector<HTMLButtonElement>("[data-mega-save]")?.addEventListener("click", () => this.callbacks.savePreset(this.host.querySelector<HTMLInputElement>("[data-mega-preset-name]")?.value.trim() || "My Continuous World"));
    this.host.querySelector<HTMLButtonElement>("[data-mega-load]")?.addEventListener("click", () => this.withSelected((id) => this.callbacks.loadPreset(id))); this.host.querySelector<HTMLButtonElement>("[data-mega-duplicate]")?.addEventListener("click", () => this.withSelected((id) => this.callbacks.duplicatePreset(id))); this.host.querySelector<HTMLButtonElement>("[data-mega-delete]")?.addEventListener("click", () => this.withSelected((id) => this.callbacks.deletePreset(id))); this.host.querySelector<HTMLButtonElement>("[data-mega-export]")?.addEventListener("click", () => this.callbacks.export());
  }
  private syncLinked(path: string, value: unknown): void { this.host.querySelectorAll<HTMLInputElement | HTMLSelectElement>(`[data-mega-path="${path}"]`).forEach((control) => { if (control instanceof HTMLInputElement && control.type === "checkbox") control.checked = Boolean(value); else control.value = String(value); }); }
  private withSelected(callback: (id: string) => void): void { const value = this.host.querySelector<HTMLSelectElement>("[data-mega-saved]")?.value; if (value) callback(value); }
}
